# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# -- General configuration ---------------------------------------------------
#
# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any Sphinx extension module names here, as strings. They can be extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones
# RJG - This file is set up to allow the sphinx-multiproject to build the docs for envirogen and revosim from a single repository
extensions = [
   "multiproject",
]

# Define the projects that will share this configuration file.
# These have to match the project environmental variable defined in the readthedocs admin menu (readthedocs project --> admin --> environmental variables)
multiproject_projects = {
    "revosim/docs": {
         "config": {
            "project": "REvoSim",
            "html_title": "REvoSim",
            "path":  "revosim/docs",
         },
    },
    "utility/envirogen/docs": {
         "config": {
            "project": "EnviroGen",
            "html_title": "EnviroGen",
            "path":  "utility/envirogen/docs",
         },
    },
}